name: CI
on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: instal svg transform pachage
        run: |
          npm i @svgr/core
          npm i @svgr/plugin-svgo
          npm i @svgr/plugin-prettier
          npm i glob
          npm run generate
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH_NAME: main
