name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update package version
        run: |
          git config --global user.email "nikobeatz91205@gmail.com"
          git config --global user.name "nikobeatz"
          npm version patch -m "update version" --force
          git add .
          git commit -m "update version"
          git push
      - name: push changes in repo
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: main
  buildComponents:
    needs: updateVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install all packages
        run: |
          npm i
          npm run generate
      - name: push changes in repo
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: main
      - name: run build bundle
        run: npm run build:bundle
      - name: push changes in repo
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: main
      - name: publish bundle
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
