name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildComponents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: patch package version
        run: |
          git config --global user.email "nikobeatz91205@gmail.com"
          git config --global user.name "nikobeatz"
          npm run release-patch
      - name: push changes in repo
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: main
      - name: install all packages
        run: |
          npm i
          npm run generate
      - name: run build bundle
        run: npm run build
      - name: push changes in repo
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: main
      - name: publish bundle
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

